"""initial migration

Revision ID: 2e6e8102fb01
Revises: 
Create Date: 2021-03-22 18:27:39.554226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e6e8102fb01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('followers', 'id')
    op.create_foreign_key(None, 'likes', 'users', ['userId'], ['id'])
    op.create_foreign_key(None, 'likes', 'posts', ['postId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.add_column('followers', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
